# Generated by Django 5.0.6 on 2024-07-30 17:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='subscription_users',
            field=models.ManyToManyField(related_name='sub_users', to=settings.AUTH_USER_MODEL, verbose_name='Subscriptions'),
        ),
    ]
