# Generated by Django 5.0.6 on 2024-07-30 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='users_likes',
            field=models.ManyToManyField(related_name='users_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
